name: fithub_user
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  image_picker: ^1.1.2
  firebase_storage: ^12.4.10
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  provider: ^6.1.5
  file_picker: ^10.2.1
  intl: ^0.20.2
  youtube_player_flutter: ^9.1.1
  flutter_rating_bar: ^4.0.1
  video_player: ^2.8.1
  flutter_pdfview: ^1.3.1
  url_launcher: ^6.2.6
  webview_flutter: ^4.2.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/fithub_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/avatar.png
    - assets/fithub_logo.png

flutter_native_splash:
  color: "#ffffff" # Background color
  image: assets/fithub_logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
